export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SET_PROFILE = 'SET_PROFILE';

export const SET_VALIDATE_COUNTER = 'SET_VALIDATE_COUNTER';
export const SET_VALIDATE_COUNTER_LOADING = 'SET_VALIDATE_COUNTER_LOADING';

export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const SET_CUSTOMERS_LOADING = 'SET_CUSTOMERS_LOADING';

export const SET_ASSETS_COUNT = 'SET_ASSETS_COUNT';
export const SET_ASSETS_COUNT_LOADING = 'SET_ASSETS_COUNT_LOADING';

export const SET_CUSTOMERS_NAME_COLLECTIONS = 'SET_CUSTOMERS_NAME_COLLECTIONS';
export const SET_CUSTOMERS_NAME_COLLECTIONS_LOADING = 'SET_CUSTOMERS_NAME_COLLECTIONS_LOADING';

export const SET_CUSTOMER_RFID_ASSETS = 'SET_CUSTOMER_RFID_ASSETS';
export const SET_CUSTOMER_RFID_ASSETS_LOADING = 'SET_CUSTOMER_RFID_ASSETS_LOADING';

export const SET_RECORD_ITEMS = 'SET_RECORD_ITEMS';
export const SET_RECORD_ITEMS_LOADING = 'SET_RECORD_ITEMS_LOADING';

export const SET_CHARTS = 'SET_CHARTS';
export const SET_CHARTS_LOADING = 'SET_CHARTS_LOADING';

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_TRANSACTIONS_LOADING = 'SET_TRANSACTIONS_LOADING';

export const SET_TIME_LINE = 'SET_TIME_LINE';
export const SET_TIME_LINE_LOADING = 'SET_TIME_LINE_LOADING';

export const SET_MESSAGES_COUNT = 'SET_MESSAGES_COUNT';
export const SET_ALERTS_COUNT = 'SET_ALERTS_COUNT';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const SET_CURRENT_WIDGET = 'SET_CURRENT_WIDGET';

export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';

export const SET_ASSETS = 'SET_ASSETS';
export const SET_ASSETS_LOADING = 'SET_ASSETS_LOADING';

export const SET_ASSETS_OUTSOURCE = 'SET_ASSETS_OUTSOURCE';
export const SET_ASSETS_OUTSOURCE_LOADING = 'SET_ASSETS_OUTSOURCE_LOADING';

export const SET_TREE_OPEN = 'SET_TREE_OPEN';
export const SET_CURRENT_ASSET = 'SET_CURRENT_ASSET';
export const SET_SITE_LOGO = 'SET_SITE_LOGO';

export const SET_NESTGRID_TAB = 'SET_NESTGRID_TAB';
export const SET_TIMELINE_TAB = 'SET_TIMELINE_TAB';
export const SET_CHART_TAB = 'SET_CHART_TAB';
export const SET_FIXIT_TAB = 'SET_FIXIT_TAB';
export const SET_RECORDIT_TAB = 'SET_RECORDIT_TAB';

export const SET_CUR_TREE_LEVEL1 = 'SET_CUR_TREE_LEVEL1';
export const SET_CUR_TREE_LEVEL2 = 'SET_CUR_TREE_LEVEL2';
export const SET_CUR_TREE_LEVEL3 = 'SET_CUR_TREE_LEVEL3';
export const SET_CUR_TREE_LEVEL4 = 'SET_CUR_TREE_LEVEL4';

export const INIT_CUR_TREE_LEVEL1 = 'INIT_CUR_TREE_LEVEL1';
export const INIT_CUR_TREE_LEVEL2 = 'INIT_CUR_TREE_LEVEL2';
export const INIT_CUR_TREE_LEVEL3 = 'INIT_CUR_TREE_LEVEL3';
export const INIT_CUR_TREE_LEVEL4 = 'INIT_CUR_TREE_LEVEL4';