export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SET_VALIDATE_COUNTER = 'SET_VALIDATE_COUNTER';

export const SET_OWNER_DATA = 'SET_OWNER_DATA';
export const SET_SECUR_DATA = 'SET_SECUR_DATA';
export const SET_OTHER_DATA = 'SET_OTHER_DATA';

export const SET_CUSTOMERS_NAME_COLLECTIONS = 'SET_CUSTOMERS_NAME_COLLECTIONS';
export const SET_CUSTOMER_RFID_ASSETS = 'SET_CUSTOMER_RFID_ASSETS';

export const SET_FIX_ITEM_COUNT = 'SET_FIX_ITEM_COUNT';
export const SET_RECORD_ITEM_COUNT = 'SET_RECORD_ITEM_COUNT';
export const SET_FIX_ITEM_LIST = 'SET_FIX_ITEM_LIST';
export const SET_RECORD_ITEM_LIST = 'SET_RECORD_ITEM_LIST';

export const SET_CHARTS_TAB1 = 'SET_CHARTS_TAB1';
export const SET_CHARTS_TAB2 = 'SET_CHARTS_TAB2';
export const SET_CHARTS_TAB3 = 'SET_CHARTS_TAB3';

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';

export const SET_TIME_LINE = 'SET_TIME_LINE';

export const SET_MESSAGES_COUNT = 'SET_MESSAGES_COUNT';
export const SET_NOTIFICATIONS_COUNT = 'SET_NOTIFICATIONS_COUNT';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const SET_CURRENT_WIDGET = 'SET_CURRENT_WIDGET';
