export default {
  auth: {
    auth_email_sent: false,
    isLoadingReset: true,
    password_reset: false,
    redirect_page: false,
  },
  patient: {
    currentWidget: 'all',
    customersData: {
      'employee': [],
      'ownership': [],
      'security': [],
      'other': []
    },
    customersLoading: false,
    customersNamesCollections: [],
    customersNameCollectionsLoading: false,
    selectedRFID: '',
    customersRFIDAssets: [],
    customersRFIDAssetsLoading: false,
    lawyerList:[],
    lawyerListLoading: false,
    documentList: [],
    documentListLoading: false,
    update_document_row: null,
    childCompanies: [],
    companiesList: [],
    companyListLoading: false,
    userList: [],
    userListLoading: true,
    recordItems: {},
    recordItemsLoading: false,
    searchCompanies: [],
    searchCompanyLoading: false,
    alertsCount: 0,
    messagesCount: 0,
    charts: {},
    chartsLoading: false,
    timeLine: {},
    timeLineLoading: false,
    transactions: [],
    transactionsLoading: false,
    comments: '',
    commentsLoading: false,
    screenHeight: 0,
    screenWidth: 0,
    assets: {},
    assetsLoading: false,
    assetsOutsource: {},
    assetsOutsourceLoading: false,
    validateCounter: {},
    validateCounterLoading: false,
    assetsCount: {},
    assetsCountLoading: false,
    main_company_selected: false,
    tree: {},
    company_tree: {},
    currentAsset: '',
    commentMessage: '',
    siteLogo: {},
    nestGridTab: 0,
    chartTab: 0,
    timelineTab: 0,
    fixitTab: 0,
    recorditTab: 0,
    pdfTab: 0,
    settingTab: 0,
    illustrationUrl: 'about:blank',
    curTree: [
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      }
    ],
  }
};